Repository cap-js/cds-typer, pull requests merged in 2024-12, with the labels that each got.

#417 Add script to automatically label dependabot prs
  .github/workflows/dependabot-skip-changelog.yml
Labels: skip changelog

#422 ci: improve release workflow
  .github/workflows/release.yml
  CHANGELOG.md
Labels: improvement

#427 fix: remove unused variable
  lib/resolution/resolver.js
Labels: improvement, skip changelog

#428 ci(release): use sed for changelog manipulation
  .github/workflows/release.yml
Labels: improvement, skip changelog

#438 fix: glitches in release workflow
  .github/workflows/prepare-next-version.yml
  .github/workflows/release.yml
Labels: skip changelog

#443 Add permissions to label workflow
  .github/workflows/dependabot-skip-changelog.yml
Labels: skip changelog
